# Generated by Django 6.1 on 2026-09-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_name', models.CharField(max_length=255)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses')),
                ('session_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='student_management_app.feestructure')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='student_management_app.students')),
            ],
            options={
                'unique_together': {('student_id', 'fee_structure_id')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student_management_app.studentfeeinvoice')),
            ],
        ),
    ]
