# Generated by Django 6.1 on 2026-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_feestructure_studentfeeinvoice_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
