# Generated by Django 6.1 on 2026-09-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_staffs_profile_pic_subjects_syllabus_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('transcript', 'Academic Transcript'), ('id_card', 'National ID / Passport'), ('certificate', 'Diploma / Certificate'), ('medical', 'Medical Document'), ('other', 'Other Document')], default='other', max_length=50)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('verification_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student_management_app.students')),
            ],
        ),
    ]
